# Configuration for the Travis continuous integration system
# ==========================================================
# 
# Travis is a free service for running automatic tests on Github repositories.
# This file configures Travis for Cylc, telling it how to install Cylc and run
# the test battery.
# 
# Test results get posted back to Github. By default Travis will run tests on any
# pull requests, adding a comment on the pull request page to say if the tests
# pass or fail, it will also test any new commits, showing the test results on
# the branch page, e.g. https://github.com/cylc/cylc/branches.
# 
# Connecting a Cylc branch
# ------------------------
# 
# To make use of Travis you will first need to create a fork of Cylc in Github.
# Log in to https://travis-ci.org using your Github credentials, it will ask for
# permission to see your repositories, set the status of branches (whether the
# build passes or fails tests) and create hooks so Travis gets notified of new
# commits.
# 
# Travis will create a list of all of your public Github repositories, you can
# enable automatic tests for a repository using the switches in this list.
# 
# More information for Travis can be found at http://docs.travis-ci.com/user/getting-started/

---
language: python
cache: pip
virtualenv:
  # we need system packages in Travis-CI's virtualenv in order to access pygtk, installed via apt-get
  system_site_packages: true
dist: xenial
addons:
  apt:
    # instruct travis-ci to always run apt-get before each build
    update: true

stages:
- unit-test
- test

env:
  global:
  - PATH="${TRAVIS_BUILD_DIR}/bin:$PATH"
  # Only run the generic tests on Travis CI.
  - CYLC_TEST_RUN_PLATFORM=false
  # Custom diff command to ignore Xlib errors (xvfb has not RANDR extension).
  - CYLC_TEST_DIFF_CMD="diff -I Xlib -u"
  matrix:
  - CHUNK="1/4"
  - CHUNK="2/4"
  - CHUNK="3/4"
  - CHUNK="4/4"

# this is the default test stage, which is used for functional-tests
install: .travis/install.sh functional-tests docs
script:
# Run tests with virtual frame buffer for X support.
- xvfb-run -a cylc test-battery --chunk $CHUNK --state=save -j 5 || (echo -e "\n\nRerunning Failed Tests...\n\n"; cylc test-battery --state=failed -j 5)
after_script: .travis/after_script.sh

jobs:
  include:
  - stage: unit-test
    install:
    - .travis/install.sh unit-tests functional-tests
    script:
    - pycodestyle --ignore=E402,W503,W504 lib/cylc lib/Jinja2Filters/*.py lib/parsec/*.py $(grep -l '#!.*\<python\>' bin/*)
    - PYTHONPATH=$(pwd -P)/lib/ pytest lib/cylc/
    after_script: true
